package tw.dd.spring.entity;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;


@Data
@Entity
@Table(name = "product")
public class Product {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private Double price;

    //  @OneToMany(mappedBy = "product")
    // private List<OrderItem> orderItems = new ArrayList<>();
    
    // Constructors, getters, and setters can be generated by Lombok
}
