package tw.syuhao.ordersystem.entity;

import java.math.BigDecimal;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import lombok.Data;


@Data
@Entity
@Table(name = "product")
public class DProduct {


    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String name;
    private BigDecimal price;

    @Column(name = "image_url")
    private String imageUrl;

    //  @OneToMany(mappedBy = "product")
    // private List<OrderItem> orderItems = new ArrayList<>();
    
    // Constructors, getters, and setters can be generated by Lombok
}
