spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: "1097626042096-kvaim9a40uijmsst8o8cejqm5eufq1qm.apps.googleusercontent.com"   # 要填的 client ID
            client-secret: "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" # 要填的 client secret
            redirect-uri: "{baseUrl}/oauth2/callback"
            scope:
              - openid
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
